In [1]:
! pip install transformers


In [6]:
! pip install modelscope

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 117.4 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 55.6 kB/s eta 0:00:0000:0100:03m


In [12]:
from transformers import GPT2LMHeadModel
from transformers import GPT2Tokenizer, GPT2Model

In [13]:
# model_hf = GPT2LMHeadModel.from_pretrained("gpt2")
model_hf = GPT2Model.from_pretrained('gpt2')
sd_hf = model_hf.load_state_dict()  # load the model weights

for k, v in sd_hf.items():
    print(k, v.shape)



2024-09-02 15:03:16,511 - modelscope - ERROR - The request model: gpt2 does not exist!


HTTPError: The request model: gpt2 does not exist!

In [14]:
from transformers import pipeline, set_seed
generator = pipeline('text-generation', model='gpt2')
set_seed(42)
generator("Hello, I'm a language model,", max_length=30, num_return_sequences=5)

/home/lucy/miniconda3/envs/xynten/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like gpt2 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

In [8]:
import torch

bias = torch.tril(torch.ones(4, 4)).view(1, 1, 4, 4)
attn = torch.rand(2, 1, 3, 3)
print(attn)
attn.masked_fill_(bias[:,:,:3,:3] == 0, float('-inf'))
print(attn)

tensor([[[[0.8784, 0.2084, 0.7126],
          [0.1251, 0.9137, 0.0748],
          [0.5890, 0.5593, 0.5225]]],


        [[[0.4644, 0.5028, 0.2455],
          [0.6156, 0.5966, 0.0530],
          [0.2058, 0.4395, 0.1298]]]])
tensor([[[[0.8784,   -inf,   -inf],
          [0.1251, 0.9137,   -inf],
          [0.5890, 0.5593, 0.5225]]],


        [[[0.4644,   -inf,   -inf],
          [0.6156, 0.5966,   -inf],
          [0.2058, 0.4395, 0.1298]]]])


In [13]:
config_args = {
            "gpt2" : dict(n_layer=12, n_head=12, n_embd=768),
            "gpt-medium" : dict(n_layer=24, n_head=16, n_embd=1024),
            "gpt-large" : dict(n_layer=36, n_head=20, n_embd=1280),
            "gpt-xl" : dict(n_layer=48, n_head=25, n_embd=1600)
        }
config_args["vocab_size"] = 50257
config_args["block_size"] = 1024
config_args

{'gpt2': {'n_layer': 12, 'n_head': 12, 'n_embd': 768},
 'gpt-medium': {'n_layer': 24, 'n_head': 16, 'n_embd': 1024},
 'gpt-large': {'n_layer': 36, 'n_head': 20, 'n_embd': 1280},
 'gpt-xl': {'n_layer': 48, 'n_head': 25, 'n_embd': 1600},
 'vocab_size': 50257,
 'block_size': 1024}

In [14]:
with open('input.txt', 'r') as f:
    text = f.read()

print(text)

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [15]:
! pip install tiktoken

In [18]:
import tiktoken
import torch
enc = tiktoken.get_encoding("gpt2")
tokens = enc.encode(text)
buffer = torch.tensor(tokens[:24+1])
x = buffer[:24].view(4, 6)
y = buffer[1:].view(4, 6)
print(x,y)

tensor([[ 5962, 22307,    25,   198,  8421,   356],
        [ 5120,   597,  2252,    11,  3285,   502],
        [ 2740,    13,   198,   198,  3237,    25],
        [  198,  5248,   461,    11,  2740,    13]]) tensor([[22307,    25,   198,  8421,   356,  5120],
        [  597,  2252,    11,  3285,   502,  2740],
        [   13,   198,   198,  3237,    25,   198],
        [ 5248,   461,    11,  2740,    13,   198]])
